
= CMake Examples
:toc:
:toc-placement!:

toc::[]

# 介绍

https://cmake.org/[CMake] 是一个跨平台的开源元构建系统，可以构建，测试和打包软件。它可以用于支持多种本机构建环境，包括苹果公司的 xcode 和微软公司的 Visual Studio.

该仓库包含了一些现代 CMake 的配置示例，这些示例以类似教程的格式进行布局。第一个示例非常基础，并且在先前示例的基础上逐渐增加了复杂性，以展示更复杂的用例。

这些示例已在 Ubuntu 16.04 上进行了测试，但应在任何支持 CMake v3.5+ 的 Linux 系统上运行

此分支适用于 CMake 3.5 及更高版本

* 有关使用 CMake 2.x 的示例，请参见分支 link:https://github.com/ttroy50/cmake-examples/tree/v2-style-includes[v2-style-includes].
* 有关使用 CMake 3.0 的示例，请参见分支 link:https://github.com/ttroy50/cmake-examples/tree/v3.0-minimum[v3.0-minimum]

image:https://travis-ci.org/ttroy50/cmake-examples.svg?branch=master["Build Status", link="https://travis-ci.org/ttroy50/cmake-examples"]

# 要求

大多数示例的基本要求为:

* CMake v3.5+
* C++ 编译器 (默认为 gcc )
* make

## 在 Ubuntu 上安装

在 Ubuntu 上安装以上内容的最简单方法如下:

[source,bash]
----
$ sudo apt-get install build-essential
$ sudo apt-get install cmake
----

一些特定的示例可能需要其他工具，包括:

* http://www.boost.org/[boost]

  $ sudo apt-get install libboost-all-dev

* https://github.com/google/protobuf[protobuf]

  $ sudo apt-get install libprotobuf-dev
  $ sudo apt-get install protobuf-compiler

* http://cppcheck.sourceforge.net/[cppcheck]

  $ sudo apt-get install cppcheck

* http://clang.llvm.org/[clang]

  $ sudo apt-get install clang-3.6

* https://ninja-build.org/[ninja]

  $ sudo apt-get install ninja-build

* link:https://conan.io[conan]

  $ sudo apt-get install python3 python3-pip
  $ sudo pip3 install conan

## Docker

Docker containers with all requirements and various versions of CMake are generated to help make testing the examples easier. These are available from the docker hub repository link:https://hub.docker.com/r/matrim/cmake-examples/[matrim/cmake-examples].

To build the full set of cmake-examples test cases you can run:

[source,bash]
----
docker run -it matrim/cmake-examples:3.5.1
cd ~ 
git clone https://github.com/ttroy50/cmake-examples.git code
cd code
./test.sh
----

For more details on build and running the docker containers link:here[dockerfiles].

# Other Links

There are many CMake tutorials and examples online. The list below includes links
to some of these which I have found helpful in my CMake journey.

  * https://web.archive.org/web/20160314094326/https://www.kdab.com/~stephen/moderncmake.pdf[Modern CMake Slides]
  * https://rix0r.nl/blog/2015/08/13/cmake-guide/[rix0r Modern CMake Blog]
  * https://cmake.org/cmake-tutorial/[Official CMake Tutorial]
  * https://gitlab.kitware.com/cmake/community/wikis/home[Official CMake Wiki]
  * https://gitlab.kitware.com/cmake/community/wikis/doc/cmake/Useful-Variables[CMake Useful Variables]
  * http://derekmolloy.ie/hello-world-introductions-to-cmake/[Derek Molloy - Intro to CMake]
  * http://techminded.net/blog/modular-c-projects-with-cmake.html[Modular C++ Projects]
  * https://web.archive.org/web/20190320121339/http://voices.canonical.com/jussi.pakkanen/2013/03/26/a-list-of-common-cmake-antipatterns/[Common CMake Anti-Patterns]
  * http://baptiste-wicht.com/posts/2014/04/install-use-clang-static-analyzer-cmake.html[Using clang static analyser with CMake]
  * https://cmake.org/pipermail/cmake/2011-April/043709.html[Static Analysis with CDash] - Includes some info about using CppCheck with CMake
  * https://samthursfield.wordpress.com/2015/10/20/some-cmake-tips/[CMake Tips]
  * https://www.johnlamp.net/cmake-tutorial.html[John Lamp - CMake Tutorial]
  * link:https://docs.conan.io[Conan Documentation]
